### ISSUE TITLE
Method called from the thread that DeepAR was not initialized in

### ISSUE THREAD

**Issue by huang840801** [DeepARSDK/videocall-android-java#11]
I just changed the license_key and agora_id and  build the app, but ran into this error.
![image](https://user-images.githubusercontent.com/39085141/157573062-210ca9fd-4f60-4d99-94dd-e3ac75835f89.png)
how to solve it.

**Comment by rs-hungnl** [comment]
try this
<img width="668" alt="Screen Shot 2022-03-13 at 17 05 06" src="https://user-images.githubusercontent.com/58771876/158054549-33d2768c-fa49-4b85-9c4e-14c3aa93efc1.png">
<img width="696" alt="Screen Shot 2022-03-13 at 17 04 54" src="https://user-images.githubusercontent.com/58771876/158054552-177cc07d-1874-4ba9-a630-fe8ecfe0cc50.png">

**Comment by KalanaPerera** [comment]
did you able to fix this?

**Comment by rs-hungnl** [comment]
the demo run on wrong thread. just change to main thread like above

**Comment by MateGasparini** [comment]
Hi all,

Thanks for reporting this issue.

We have pushed a fix in 451fd1d7.
Also, thanks for proposing the solution, @rs-hungnl.
