### ISSUE TITLE
switch camera not working

### ISSUE THREAD

**Issue by nsgdev** [DeepARSDK/videocall-android-java#7]
when i am calling mRtcEngine.switchCamera(); it is giving response -1. 
In docs, they say 
0: Success.
< 0: Failure.
But what is the error I couldn't find it? Please help.

**Comment by JelenaKB** [comment]
You can find an example of camera switching in the [quickstart project](https://github.com/DeepARSDK/quickstart-android-java), recently updated to support CameraX.

You seem to be calling an agora function to control the camera, but the camera lens should be set directly 

For example:

`CameraSelector cameraSelector = new CameraSelector.Builder().requireLensFacing(CameraSelector.LENS_FACING_FRONT).build();`

**Comment by AndroXStudiO** [comment]
i am facing same problem but why?
